# Generated by Django 5.1.4 on 2024-12-20 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_Name', models.CharField(max_length=50)),
                ('study_Description', models.CharField(max_length=250)),
                ('study_Phase', models.CharField(choices=[('P1', 'Phase I'), ('P2', 'Phase II '), ('P3', 'Phase III'), ('P4', 'Phase IV ')], default='P1', max_length=3)),
                ('Sponsor_Name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='study_management_app.sponsors')),
            ],
        ),
    ]
